### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ntuzer** [ntuzer/EvenTide#2]
- Backend: DB users table, user and session model, users controller, users views
 - Redux Loop: Ajax calls, sign up sign in logout actions, sessions reducer
 - Presentational Components
 - Styling
 - Smooth, bug-free navigation
 - Adequate and appropriate seeds

**Comment by ajansel** [comment]
General 
- [x] Add a body to your comment above that describes what you had to do for this MVP. You can see an example here that will help: https://github.com/appacademy/bluebird/issues/20 
- [x] Your wiki needs a link to your heroku site at the top 
- [x] Your homepage needs styled for this MVP

Sign up / Sign In 
- These transitions look great! Excellent work so far. I only had a few comments 
- [x] When I switch to the `Sign up` page, then close the modal, and then click on the `Sign In` button the errors from the `Sign up` page are still there but should be cleared. You could probably fix this by clearing errors when the modal closes. 
- [x] The first time I click demo user it fails and renders an error `Invalid credentials` and then I have to manually click `submit` for it to sign in the user, and it looks like this is only because it filled in the state with the credentials. 
- [x] When I fill in an email and password on either page and then flip to the other page the email and password stays filled in. It's hard to say whether they should both clear or not, there could be an argument made either way. But, I think at the very least the password should clear. You could set the state of password back to an empty string in a life cycle method. 
- [x] I think where you say `Or would you like to log in instead?` the `log in` part should be a different color so that it is clear they can click on it. Same goes with the `sign up` part when trying to log in. 
- [x] Ideally, when the errors render, it shouldn't push the input boxes down. Rather, you should leave space such that the errors fill the space when the render but don't need to force everything else down.

Otherwise, this is looking good! Great work so far. Just comment below if you have questions. You can check the checkboxes as you finish things and then leave a comment letting me know when you're finished with them so I can mark off this MVP. Keep up the good work!

**Comment by ajansel** [comment]
- [x] Also, you should now begin removing your debuggers once you're finished testing with them

**Comment by ajansel** [comment]
This looks great! Excellent work in addressing these! MVP complete!
